### ISSUE TITLE
ToBeEmpty assertion in jest-native is also used in jest-extended

### ISSUE THREAD

**Issue by AugustinLF** [testing-library/jest-native#102]
**Describe the feature you'd like:**

Jest-Extended has an assertion named the same as jest-native's one:

-> https://github.com/jest-community/jest-extended#tobeempty
-> https://github.com/testing-library/jest-native#tobeempty

When both libs are used in the same project, the version of jest-extended overwrites the one from jest-native.

`@testing-library/jest-dom` has had the same problem https://github.com/testing-library/jest-dom/issues/216 and they renamed their matcher to `toBeEmptyDOMElement `.

**Suggested implementation:**

I wished we could have the same matcher on both platforms, but `toBeEmptyDOMElement` doesn't make sense on native, so I'd suggest something like `toBeEmptyElement`, or `toBeEmptyNode`.

**Teachability, Documentation, Adoption, Migration Strategy:**

We should do like `@testing-library/jest-dom`, i.e. add the new matcher and tag the current one as deprecated.

**Comment by mdjastrzebski** [comment]
I am for `toBeEmptyElement`. @AugustinLF could you submit PR for that?

**Comment by gquaresma-godaddy** [comment]
Hey @mdjastrzebski can I assume this issue?

**Comment by joaoGabriel55** [comment]
Hey @mdjastrzebski can I assume this issue?
