### ISSUE TITLE
Matcher toBeDisabled does not take into account the editable prop of TextInput

### ISSUE THREAD

**Issue by HugoChollet** [testing-library/jest-native#129]
### Problem / Feature Request

The matcher `toBeDisabled` does not take into account the editable prop of the `<TextInput />` component. 

```tsx
render(<TextInput testId="input" editable={false}/>)
expect(screen.getByTestId("input")).toBeDisabled() // will fail
```
In the [readme.md](https://github.com/testing-library/jest-native#tobedisabled), it says:
 >Check whether or not an element is disabled from a user perspective

In my opinion when we have `<TextInput editable={false}/>` the element appears to be disabled from a user perspective 

What do you think of adding the `editable` prop into the checks of the matcher `toBeDisabled` ?

### Environment

@testing-library/react-native version: 11.3.0
jest-preset: react-expo
react-native version: 0.69.6
node version: 18.11

**Comment by MattAgn** [comment]
Agreed, that would be a nice addition to have

**Comment by mdjastrzebski** [comment]
@HugoChollet Would you like to contribute a PR for this?

**Comment by HugoChollet** [comment]
close by #135
