### ISSUE TITLE
Missing (dist) index.js which exports all matchers for library usage

### ISSUE THREAD

**Issue by jgornick** [testing-library/jest-native#130]
### Relevant code or config:

```js
const jestNativeMatchers = require('@testing-library/jest-native')
```
### What you did:

Upgrade `@testing-library/jest-native` from `4.0.2` to `5.3.0`

### What happened:

`Cannot find module '@testing-library/jest-native ...`

### Reproduction:

Try to import all or individual matchers using the code example in the README.md.

### Problem description:

After inspecting the package, the `main` entry field in `package.json` points to a `dist/index.js`, which doesn't exist. 

### Suggested solution:

Re-add the barrel file (dist/index.js) to export the matchers. You can automate this part of the build too using [barrelsby](https://github.com/bencoveney/barrelsby).

### Can you help us fix this issue by submitting a pull request?

Yes, I could help submit a PR. I wanted to log the issue first to see if this is intended 😄

**Comment by mdjastrzebski** [comment]
@jgornick It seems that this might be related to TS migration done with ver5.0. Pls submit a PR, can it be done using `tsc`?

**Comment by jgornick** [comment]
PR created #132
