### ISSUE TITLE
Add toBeOnTheScreen matcher to src/index exports

### ISSUE THREAD

**Issue by stellarskye** [testing-library/jest-native#138]
Problem: Can't selectively import the `toBeOnTheScreen` matcher as described [in the readme](https://github.com/testing-library/jest-native/blob/main/README.md?plain=1#L109-L116)

Proposal: Add the recently added (and helpful) [toBeOnTheScreen](https://github.com/testing-library/jest-native/pull/125) to the [index file](https://github.com/testing-library/jest-native/blob/main/src/index.ts).

**Comment by mdjastrzebski** [comment]
@stellarskye thanks for reporting this! Fixed it.
