### ISSUE TITLE
toBeOnTheScreen() not Working With React-Native

### ISSUE THREAD

**Issue by komalharmale** [testing-library/jest-native#139]
- `react-native` or `expo`:
- `@testing-library/react-native` version:
- `jest-preset`:
- `react-native` version:
- `node` version:

### Relevant code or config:

```js
const your = (code) => 'here';
```

**Comment by komalharmale** [comment]
I have create one simple component in that I have write the code for single button 
like this 

  return(
    <View style={styles.root}>
        <View  testID="child" style={styles.header}>List of numbers from 1 to 20</View >
        <TouchableOpacity
       testID='button'
              onPress={()=>navigation.navigate('Dashboard')}
              style={styles.submitcontainer}>
               <Text style={{color:'#FFFFFF',backgroundColor:'blue'}}>Go To Login Screen</Text>
             </TouchableOpacity>
    </View>
  );

}


This is my test.js file where i am trying to check is element is available on screen but jest is throwing error while running the command

  render(<Profile/>);
  const child = screen.getByTestId('child')
  expect(child).toBeOnTheScreen();

    const header = await screen.findByText('List of numbers from 1 to 20');
    expect(header).toBeOnTheScreen();

nothing works

**Comment by mdjastrzebski** [comment]
@komalharmale I am unable to understand the exact issue you are facing. Could you use [RNTL basic example](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic) app to build a minimal reproduction repository that showcases your issue?

**Comment by mdjastrzebski** [comment]
@komalharmale Closing as not actionable without response from OP.

**Comment by thespacemanatee** [comment]
I got this error as well using latest version of the libraries

**Comment by komalharmale** [comment]
@mdjastrzebski @thespacemanatee I AM facing above issue because of I forgot to install 'testing-libraty/jest-native` library.
Now it's working as expected.
