### ISSUE TITLE
toBeVisible ignores opacity via color property

### ISSUE THREAD

**Issue by pipedreambomb** [testing-library/jest-native#152]
- `react-native` or `expo`:  Expo 47
- `@testing-library/react-native` version: ^12.0.0-rc.0
- `jest-preset`: "jest-expo"
- `react-native` version: "0.70.5"
- `node` version: v14.21.2.

### Relevant code or config:

```js
import React from 'react'
import { Text } from 'react-native'
import { render, screen } from '@testing-library/react-native'

test('Invisible text with property', () => {
  render(<Text style={{ opacity: 0 }}>I am invisible</Text>)

  expect(screen.getByText('I am invisible')).not.toBeVisible()
})

test('Invisible text with color', () => {
  render(<Text style={{ color: '#fff0' }}>So am I!</Text>)

  expect(screen.getByText('So am I!')).not.toBeVisible()
})

```
Produces test output: 
```
 FAIL  features/cell/newFile.test.jsx (11.251 s)
  ✓ Invisible text with property (416 ms)
  ✕ Invisible text with color (415 ms)

  ● Invisible text with color

    expect(element).not.toBeVisible()

    Received element is visible:
      <Text
        children="So am I!"
        style={
          {
            "color": "#fff0",
          }
        }
      />

      12 |   render(<Text style={{ color: '#fff0' }}>So am I!</Text>)
      13 |
    > 14 |   expect(screen.getByText('So am I!')).not.toBeVisible()
         |                                            ^
      15 | })
      16 |

      at Object.<anonymous> (features/cell/newFile.test.jsx:14:44)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        11.874 s
```

### What you did:

I was converting my old Enzyme tests to use React Native Testing Library and trying to take advantage of the Jest Native idiomatic assertions. 

### What happened:

My test failed because I was using `color: '#fff0'` or `color: '#ffff'` to toggle visibility of some text in my React Native app. According to `expect(...).not.toBeVisible()`, it was visible, but this ignores the alpha element of the color hexadecimal code.

### Reproduction:

See above.

### Problem description:

It's not a major issue but it means I have to change my production code to fix the test when I think the test should just work as is. Perhaps you won't think it's important but I didn't see it reported in the Issues tab, so I'm reporting it.

### Suggested solution:

Add a further check function in `to-be-visible.ts` which checks color for the optional opacity character(s) in hex string and also in `rgba(x,x,x,x)`.

### Can you help us fix this issue by submitting a pull request?

Yes, probably, though I'm not super familiar with the various versions of this that exist (probably rgba, 6 digit hashes, etc). The relevant information in React Native appears to be [here](https://reactnative.dev/docs/colors).

**Comment by mdjastrzebski** [comment]
I think that useing font color for determining opacity is not a generally good idea, as other parts of the `Text` element might make it visible, e.g. background color or border. 

Also, semantically this is not a hidden element, but rather an element where one piece of it is made transparent.

In the long-run I would suggest refactoring your code to tweak e.g. `opacity` style (which affects the whole view and is recognized by `toBeVisible` matcher). 

As a temporary workaround The only you can create a helper function that will check whether the element uses a transparent color and use it something like

```
expect(hasTransparentColor(getByRole(...))).toBeTruthy().
```

**Comment by pipedreambomb** [comment]
Yes, I've updated my production code to use `opacity`, thanks. Feel free to close the issue if you don't see this behaviour as a problem. I understand your perspective and it's a judgement call I can respect.
