### ISSUE TITLE
Property 'toHaveTextContent' does not exist on type 'JestMatchers<ReactTestInstance | null>'.ts(2339)

### ISSUE THREAD

**Issue by parnekov** [testing-library/jest-native#165]
If you work with typescript test files and received this error, just put **import '@testing-library/jest-native';** to the top of the file.

**Comment by jacksonsmith** [comment]
Hey @parnekov  do you have installed `@testing-library/jest-dom` dependency ?

**Comment by mdjastrzebski** [comment]
Duplicate of #146. 
Here is direct link to recommended workarounds: https://github.com/testing-library/jest-native/issues/146#issuecomment-1539084484
