### ISSUE TITLE
"SyntaxError: Cannot use import statement outside a module" after upgrading to react-native 0.72.4

### ISSUE THREAD

**Issue by gabrielfurini** [testing-library/jest-native#191]
Hello folks, after upgrading RN from 0.72.3 to 0.72.4 (expo-doctor recommended this change), my tests suites stopped working.

I'm having the following error:

```
    <my-project-path>/node_modules/@testing-library/jest-native/node_modules/react-native/index.js:14
    import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (../../node_modules/@testing-library/jest-native/dist/to-be-visible.js:4:24)
      at Object.<anonymous> (../../node_modules/@testing-library/jest-native/dist/extend-expect.js:6:25)
      at Object.<anonymous> (../../node_modules/@testing-library/jest-native/extend-expect.js:1:103)
```

- `react-native` or `expo`: expo (SDK 49)
- `@testing-library/react-native` version: 12.3.0
- `jest-preset`: `jest-expo` at version 49.0.0
- `react-native` version: 0.72.4
- `node` version: 16.16.0

Do you have any clue what happened and how can this be fixed?

Thank you!

### Relevant code or config:

This is my `jest.config.ts` file:

```
const config = {
  preset: "jest-expo",
  transformIgnorePatterns: [
    "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|@sentry/.*|native-base|react-native-svg)",
  ],
  testPathIgnorePatterns: ["/__utils__/"],
  setupFiles: ["./jest.setup.js"],
  setupFilesAfterEnv: ["@testing-library/jest-native/extend-expect"],
};

module.exports = config;
```

### What you did:

Just upgraded the RN version to 0.72.4

**Comment by mdjastrzebski** [comment]
@gabrielfurini Not sure about the cause here. You could try to compare you setup to [RNTL's basic example](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic) app which includes latest versions for RN, RNTL and Jest Native packages and works correctly.

I would generally suspect that to be some Babel-related config issue.

**Comment by gabrielfurini** [comment]
@mdjastrzebski I could fix the error about `jest-native/extend-expect.js` just adding `"@testing-library"` into `transformIgnorePatterns` property of `jest.config.js`.

But then countless errors related to modules that don't support the new architecture TurboModules/Fabric of React Native emerged. 😢 

I suspect I cannot upgrade to the 0.72.4 until these modules support the new architecture.
Or do we have a way of bypassing these third-parties modules or to make them to use the old architecture while only testing?

**Comment by gabrielfurini** [comment]
@mdjastrzebski Nevermind! I could find the issue and it was simply related to some TSC errors that were not being show at a first-glance. Jest logs were not friendly and pulled the wool over my eyes. 😭 

I really appreciate your time jumping into it. Thank you!
I'm closing the issue.
