### ISSUE TITLE
Correct setup in react-native typescript project

### ISSUE THREAD

**Issue by yuritoledo** [testing-library/jest-native#21]
Hello,

There are any correct setup to use with TS?

I try to import `import '@testing-library/jest-native/extend-expect'` in `File.test.tsx`, but it falls.

Autocomplete and functions doesnt works.

Versions: 
```json
   "@testing-library/jest-native": "^3.1.0",
    "@testing-library/react-native": "^5.0.3",
```
Jest config: 
```json
 "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base)"
    ],
    "setupFilesAfterEnv": [
      "./src/setupTest.js"
    ]
  }
```

**Comment by sjungwirth** [comment]
possibly same issue as https://github.com/testing-library/jest-native/issues/25

I fixed it in my project by adding my own type file with the fix:

```
import { ReactTestInstance } from 'react-test-renderer';

declare global {
  namespace jest {
    interface Matchers<R, T> {
      toBeDisabled(): R;
      toContainElement(element: ReactTestInstance | null): R;
      toBeEmpty(): R;
      toHaveProp(attr: string, value?: any): R;
      toHaveTextContent(text: string | RegExp, options?: { normalizeWhitespace: boolean }): R;
      toBeEnabled(): R;
      toHaveStyle(style: object[] | object): R;
    }
  }
}
```

**Comment by yuritoledo** [comment]
Thank you bro, for sharing. I had the same think as you

**Comment by frontendwizard** [comment]
I'm facing this same issue on 4.0.4

**Comment by idetatsu** [comment]
I am facing this on 4.0.5.

**Comment by 7assenTlili** [comment]
Facing this with 4.0.11

**Comment by mdjastrzebski** [comment]
@7assenTlili take a look at RNTL + Jest Native setup in RNTL basic example: https://github.com/callstack/react-native-testing-library/tree/main/examples/basic

Has correct setup for TypeScript projects.

Note: you should import `@testing-library/jest-native/extend-expect` once, in your `jest-setup.ts` file.

**Comment by 7assenTlili** [comment]
@mdjastrzebski Thanks for the quick reply. Something that I should mention is that we have Detox setup in the project as well, so  importing `@testing-library/jest-native/extend-expect` in jest-setup.js file does not work as it throws an error for `expect is not defined` (probably because jasmine expect is the global one) so we are importing it as `setupFilesAfterEnv: ['@testing-library/jest-native/extend-expect']`.

**Comment by mdjastrzebski** [comment]
Yes, I mean `jest-setup.js` that is imported as `setupFilesAfterEnv`

**Comment by IlirBajrami** [comment]
Still having the issue in version `^5.3.0`. 
@sjungwirth solution fixed it.

**Comment by mdjastrzebski** [comment]
@IlirBajrami this issue is closed. Pls create a new issue and **include a minimal repository** that showcases the issue you are facing. This is the only way for anyone to have a chance at helping you solve it.

**Comment by douglasjunior** [comment]
For the types, just add `@testing-library/jest-native` in your `tsconfig.json` types.

```json
{
  "compilerOptions": {
       "types": ["react-native", "jest", "@testing-library/jest-native"],
```

I think it would be interesting to add this instruction in the docs.

**Comment by SethDavenport** [comment]
`compilerOptions.types` in TSConfig.json is problematic though if you are relying on TS picking up other `@types` packages from your `node_modules` folder; when you specify this option, it overrides TS's default behaviour.

See https://www.typescriptlang.org/tsconfig#types

**Comment by douglasjunior** [comment]
> `compilerOptions.types` in TSConfig.json is problematic though if you are relying on TS picking up other `@types` packages from your `node_modules` folder; when you specify this option, it overrides TS's default behaviour.
> 
> See https://www.typescriptlang.org/tsconfig#types

I think it's ok, because the "types" is used to load global types that are not imported directly in the code.

At least in my projects, there are very few cases of global types like this.
