### ISSUE TITLE
Update type for Matchers to match @types/jest

### ISSUE THREAD

**Issue by sjungwirth** [testing-library/jest-native#25]
What:

@types/jest recently had some updates to correct the type for Matchers. This update is a breaking change for any TypeScript project that uses expect.extend.

See: DefinitelyTyped/DefinitelyTyped#39243

Why:

@testing-library/jest-native defines the Matchers type in extend-expect.d.ts.

**Comment by brunohkbx** [comment]
@sjungwirth thanks for reporting. Would you be able to open a pull request to address that?
