### ISSUE TITLE
Current project support status

### ISSUE THREAD

**Issue by nickmccurdy** [testing-library/jest-native#34]
I've noticed `@testing-library/jest-native` has been deprecated. Should this package also be deprecated, or is it actively used elsewhere?

**Comment by brunohkbx** [comment]
I think it's still actively used. @kentcdodds invited @thymikee and I to help maintain

**Comment by nickmccurdy** [comment]
Thanks. Should I love this then? Or could it potentially be useful to still deprecate or pivot this issue into supporting the new callstack native testing library?

**Comment by thymikee** [comment]
This project is fine and not deprecated. Where is it stated?

**Comment by kentcdodds** [comment]
Yeah, this is still actively maintained.
