### ISSUE TITLE
toBeDisabled does not work with styled-components

### ISSUE THREAD

**Issue by automatensalat** [testing-library/jest-native#35]
- `react-native` or `expo`: react-native
- `@testing-library/react-native` version: 3.3.0
- `jest-preset`: not installed, but I'm sure this doesn't matter
- `react-native` version: 0.63.2
- `node` version: 10
- `styled-components` version: 5.1.1

### Relevant code or config:

```json
{ 
  "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.2",
    "styled-components": "^5.1.1",
  }
}
```

Consider this code. It renders a button styled with `styled-components`.

```tsx
// MyComponent.tsx
export function MyComponent() {
  return (<StyledButton testID="testButton" disabled>
        <Text>Hello</Text>
      </StyledButton>);
}

const StyledButton = styled.TouchableOpacity``;
```

This test checks whether the button is disabled.
```tsx
// MyComponent.test.tsx
it("disables the button", () => {
    const renderer = render(
      <MyComponent />,
    );

    expect(renderer.getByTestId("testButton")).toHaveProp("disabled", true); // passes
    expect(renderer.getByTestId("testButton")).toBeDisabled(); // fails
  });
```

### What you did:

I wrote the test above

### What happened:

The test fails with this message:

```
expect(element).toBeDisabled()

    Received element is not disabled:
      Object {
      "props": Object {
        "children": <Text>
          Hello
        </Text>,
        "disabled": true,
        "testID": "testButton",
      },
    }

```

### Reproduction:

I might do that later and edit this bug report, I think it's reproducable with the information above

### Problem description:

The test fails because `toBeDisabled()` checks for the name of the component to be any of the known RN types. However styled-component wraps those components and doesn't retain the name. In `dist/utils.js` the function `getType()` checks for the name, and the component name returns `Styled(Component)` for `type.displayName`. So, it does not match the string `TouchableOpacity` and the matcher returns false. 

### Suggested solution:

IDK, the two alternatives that I can think of now are a) not checking for the name at all and b) unwrapping that component somehow if we 'detect' it's a styled-component. Not sure if that's possible though.

### Can you help us fix this issue by submitting a pull request?

I guess, depends on what we could do to solve this

**Comment by automatensalat** [comment]
Well, I noticed there is [this](https://github.com/testing-library/jest-native/issues/23) issue which also deals with `toBeDisabled`. However it seems this is more about `TouchableOpacity`. The issue I'm having with `styled-components` also holds true for other components like `Button` though: 
```tsx 
export function MyComponent() {
return (<StyledButton
        testID="testButton"
        title="Hello"
        disabled
        onPress={() => {}}
      />
    </View>);
}

const StyledButton = styled.Button``;
```

Here however we might have a chance to unwrap the component since the `displayName` returns `Styled(Button)` in this case.

**Comment by thymikee** [comment]
Does it happen with the latest version of `@testing-library/react-native`? It's v7 now

**Comment by automatensalat** [comment]
No! Good call. I had an older library version installed. Thank you.

**Comment by thymikee** [comment]
Glad it works :)
