### ISSUE TITLE
toHaveProp does't work properly with @testing-library/react-native: 7.0.2 (latest)

### ISSUE THREAD

**Issue by yonatan-altaraz** [testing-library/jest-native#37]
- `react-native`: "^0.59.6"
- `@testing-library/react-native` version: "7.0.2"
- `node` version: v12.12.0

### Relevant code or config:

this code is coppied from jest-native -> src/to-have-prop.js:
```js
const isAllowed = VALID_ELEMENTS.includes(element.type);
```
it assumes element.type is a string, but in the new testing-library version when accessing the element using `getByText` accessor, i get an object with `type: {... , displayName: 'string', ...}`, so `isAllowed` is false and the test passes with wrong expected value.

### What you did:
```js
test('.toHaveProp', () => {
  const { queryByTestId, getByText } = render(
    <View>
      <Text allowFontScaling={false} testID="text">
        text
      </Text>
      <Button disabled testID="button" title="ok" />
    </View>,
  );
  expect(getByText('text')).toHaveProp('allowFontScaling', 'wrongValue')
```

### What happened:

this example test does not fail even though a wrong expected value was provided

### Reproduction:
[here's a branch that recreates the problem](https://github.com/khealth/jest-native/tree/recreate_toHaveProp_bug)
i've made minimum changes to make it work with the new @testing-library/react-native version, also removed other tests cause it caused other failures.

### Suggested solution:
check the element.type type to see if it's a string or an object.

### Can you help us fix this issue by submitting a pull request?
i've opened [a pr that fixes it](https://github.com/testing-library/jest-native/pull/36)

**Comment by brunohkbx** [comment]
closed this in #36
