### ISSUE TITLE
Support @testing-library/react-native 7.0

### ISSUE THREAD

**Issue by brunohkbx** [testing-library/jest-native#43]
**Describe the feature you'd like:**
We should bump `@testing-library/react-native` from 6.0 to 7.0 and fix the broken tests in order to fully support v7.0.

**Suggested implementation:**
Follow these [instructions](https://callstack.github.io/react-native-testing-library/docs/migration-v7/#guide-for-testing-libraryreact-native-users)

**Comment by thymikee** [comment]
Let's do it please, happy to review!
