### ISSUE TITLE
Extending expect in typescript project

### ISSUE THREAD

**Issue by jbolotin** [testing-library/jest-native#48]
### Problem description:
Thanks for maintaining this great library! I'm super excited to have found it and to start using it to more easily test react native components.

I'm trying to add this to a typescript RN project, but I'm having trouble getting this to properly extend `expect`. I've tried following [the instructions](https://callstack.github.io/react-native-testing-library/docs/getting-started#additional-jest-matchers) in react-native-testing-library and [here](https://github.com/testing-library/jest-native#usage), but in both cases, typescript fails to recognize the new extensions to `expect`

### Notes:

I see that #39 should have fixed this issue, but I'm definitely still experiencing it. I'm happy to try out a few more things or provide additional details, but I'm not sure how to proceed testing this out right now.

**Comment by brunohkbx** [comment]
@jbolotin have you found a solution?

**Comment by maxckelly** [comment]
Did you find a solution? I'm facing this issue at the moment.

**Comment by michaelgmcd** [comment]
@brunohkbx You need to make sure that `@testing-library/jest-native` is imported in a ts file. You can do it at the top of a test file or somewhere like setup.ts
```
import '@testing-library/jest-native';
```
