### ISSUE TITLE
Property 'toHaveStyle' does not exist on type 'JestMatchers<any>'

### ISSUE THREAD

**Issue by jorgeruvalcaba** [testing-library/jest-native#72]
I've just installed `jest-native` and when I try to use `toHaveStyle()` I got this error:

<img width="451" alt="Screen Shot 2021-12-23 at 4 46 12 p m" src="https://user-images.githubusercontent.com/7416811/147297312-bd2c0c72-e240-4edc-a580-1a77ad886b95.png">

This is the complete example:
```tsx

const commonStyles: TextStyle = {
  fontFamily: 'ProximaNova',
  fontSize: 14,
  lineHeight: 20,
  color: getColor('gray-100'),
}

describe('TextInfo', () => {
  it('should render the given text with default styles', () => {
    const { getByText } = render(<TextInfo>{sampleText}</TextInfo>)
    expect(getByText(sampleText)).toHaveStyle(commonStyles)
    expect(getByText(sampleText)).toBeTruthy()
  })

  it('should render the given text with custom styles', () => {
    const { getByText } = render(
      <TextInfo style={{ marginBottom: 8 }}>{sampleText}</TextInfo>,
    )
    expect(getByText(sampleText)).toHaveStyle({
      ...commonStyles,
      marginBottom: 8,
    })
    expect(getByText(sampleText)).toBeTruthy()
  })
})

```

How can I get rid off this error?

**Comment by technyx-ali-rehman** [comment]
Same here 
![image](https://user-images.githubusercontent.com/48116823/150329354-7a44bb70-1be2-41ae-b173-d3da000b3142.png)

**Comment by flo-sch** [comment]
It seems like referencing this library directly from within the jest config causes the types not to be loaded. I guess this is how jest & TypeScript together works, not sure if there is a way to automatically fix it.

But a simple workaround is to point the script to a TypeScript file that just imports the library:

Change from this:

```js
// jest.config.js
module.exports = {
  // [...]
  setupFilesAfterEnv: ['@testing-library/jest-native/extend-expect'],
};
```

To this:

```ts
// jest.setupFilesAfterEnv.ts
import '@testing-library/jest-native/extend-expect'
```

```js
// jest.config.js
module.exports = {
  // [...]
  setupFilesAfterEnv: ['<rootDir>/jest.setupFilesAfterEnv.ts'],
};
```

**Comment by friederbluemle** [comment]
Related: #7

One more thing worth mentioning (in case it wasn't obvious):

Make sure the test setup file ends in `.ts` (or `.tsx`), and is **not excluded** in the default tsconfig used by your IDE (e.g. by sitting in a directory that is part of `exclude` in `tsconfig.json`).

**Comment by zhiqingchen** [comment]
> Related: #7
> 
> One more thing worth mentioning (in case it wasn't obvious):
> 
> Make sure the test setup file ends in `.ts` (or `.tsx`), and is **not excluded** in the default tsconfig used by your IDE (e.g. by sitting in a directory that is part of `exclude` in `tsconfig.json`).

it works, but it will cause `setup.ts` to be builded

**Comment by friederbluemle** [comment]
> > Related: #7
> > One more thing worth mentioning (in case it wasn't obvious):
> > Make sure the test setup file ends in `.ts` (or `.tsx`), and is **not excluded** in the default tsconfig used by your IDE (e.g. by sitting in a directory that is part of `exclude` in `tsconfig.json`).
> 
> it works, but it will cause `setup.ts` to be builded

That's correct. If your project is published and you want to only ship compiled source files (not tests or setup.ts), then you would need two separate `tsconfig.json` files. For example, one `tsconfig.release.json` _extending_ `tsconfig.json`, which _excludes_ tests. In your `package.json` you'd have a `build` script like: `tsc -p tsconfig.release.json`. Your IDE will pick up `tsconfig.json` which _includes_ tests to function properly.

**Comment by roni-castro** [comment]
This problem also happened with me when I added `"include": ["src/**/*"]` to the `tsconfig.json`

**Comment by mdjastrzebski** [comment]
Closing as stale.

@jorgeruvalcaba If the issue persists with the latest release v5.0.0. Please submit a new issue with minimal repro repository. For our convenience please use [`examples/basic`](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic) from React Native Testing Library as a base for the PR.

**Comment by alexamy** [comment]
Have the same problem. Using `jest-expo` and typescript test file with explicit jest import.
[Suggested solution](https://github.com/testing-library/jest-native/issues/72#issuecomment-1049875456) doesn't work.

**Comment by mdjastrzebski** [comment]
@alexamy Please submit a new issue with minimal repro repository. For convenience please use [examples/basic](https://github.com/callstack/react-native-testing-library/tree/main/examples/basic) from React Native Testing Library as a base for the PR.

**Comment by PSainz** [comment]
Try adding that to your test file, it’s what got rid of the error for me.

import '@testing-library/jest-dom';

**Comment by marocas** [comment]
In my case, I just converted the `jest.config.js` to `jest.config.ts` and instead of `required('@testing-library/jest-dom')` `import '@testing-library/jest-dom'`.

```TS
// jest.config.js
/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  ...
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  ...
}
```

```TS
// jest.setup.ts
import '@testing-library/jest-dom'
```
