### ISSUE TITLE
feat: toBeFocused

### ISSUE THREAD

**Issue by chris-chapin** [testing-library/jest-native#74]
**Describe the feature you'd like:**

A new matcher for testing if an element is focused.

Similar to what Detox has: https://wix.github.io/Detox/docs/api/expect#tobefocused

**Comment by HudiDev** [comment]
have no idea why react-testing-library has a focus feature but not react-native-testing-library

**Comment by mdjastrzebski** [comment]
Interesting idea. I'm not sure if feasible, as RNTL does it's renders using React Test Renderer and not React Native renderer, and hence it's runtime environment is quite limited. In contract RTL uses real React DOM renderer working with Js DOM to have full-blown browser environment.

@chris-chapin would you be willing to build a PR for this?

**Comment by mdjastrzebski** [comment]
Closing as stale.

@chris-chapin if you find any suitable solution to the native/JS issue I've described above feel free to submit a PR for this.

**Comment by kopax-polyconseil** [comment]
Hello,

In one of our test, the onFocus is setting the focus in a state and then display a list of clickable choice. I am not able to test it because this feature is not supported.

Can we reopen this please?

**Comment by mdjastrzebski** [comment]
@kopax-polyconseil afaik supporting `toBeFocused()` in Jest Native/React Native Testing Library/React Test Renderer is not possible due to lack of runtime environment that would manage the focus. Original (web) React Testing Library has [jsdom](https://github.com/jsdom/jsdom) to simulate browser env, while Detox runs using real React Native environment on device/emulator.

In our case someone would have to create such non-standard environment, moreover it would have to be maintained to match changes in React Native.

**Comment by export-mike** [comment]
not ideal but its something at least, I ended up wrapping my input with a view with a conditional test_id to search for in my tests

```js
<View testID={`${testID}_${autoFocus ? 'focused' : 'not_focused' }>...
```

**Comment by EGurney** [comment]
> not ideal but its something at least, I ended up wrapping my input with a view with a conditional test_id to search for in my tests
> 
> ```js
> <View testID={`${testID}_${isFocus ? 'focused' : 'not_focused' }>...
> ```

This makes me so sad that we have to do this.

**Comment by NerdyDave2017** [comment]
@mdjastrzebski you mentioned creating a non-standard environment to test on device/emulator. Has this being achieved yet?

**Comment by nderevj** [comment]
Here's hack I like to use:

```typescript
const focusSpy = jest.spyOn(TextInput.prototype, 'focus');
// Perform / simulate some action...
expect(focusSpy).toHaveBeenCalled();
```
