### ISSUE TITLE
toBeEmpty is incorrectly returning false when children's prop on element is false

### ISSUE THREAD

**Issue by fgc29** [testing-library/jest-native#8]
The **toBeEmpty** method is incorrectly returning false when children's prop on the queried element is false.  The example below is for a conditionally rendered child.

This works as expected (props => children => undefined)

```
     const { getByTestId } = render(<View testID="empty"></View>);

     expect(getByTestId('empty')).toBeEmpty();
```
but in this example the **toBeEmpty** method incorrectly returns false... (props => children => false)

```
      const conditional = false
      const { getByTestId } = render(<View testID="notEmpty">{ conditional && <View testID="empty"/> }</View>);

      expect(getByTestId('notEmpty')).toBeEmpty();
```

**Comment by bcarroll22** [comment]
Hey this makes sense because the children prop isn't "empty in the sense that it isn't an empty React object or an empty array. That said, for a user, the element will appear to be empty. 

Do you have a suggested fix that would make this work for your use case?

**Comment by bcarroll22** [comment]
I'm going to close this one due to inactivity. If anyone in the future stumbles across this and would like to submit a suggested fix as a PR, I'm all for it 👍
